<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0993" ignored="1" name="UnitTestsforCalculator" tests="30" failures="6" timestamp="01 Jun 2017 16:53:24 GMT" time="0.082" errors="0">
  <testcase name="cosineOfDouble" time="0.005" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cosineOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cosineOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="cotangetOfdouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [0.64209261593] but found [0.7615941559557649]">
      <![CDATA[java.lang.AssertionError: expected [0.64209261593] but found [0.7615941559557649]
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="cotangetOfdouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [3.82054149728] but found [0.25055040799817446]">
      <![CDATA[java.lang.AssertionError: expected [3.82054149728] but found [0.25055040799817446]
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="cotangetOfdouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [1.07342614855] but found [0.6351489523872873]">
      <![CDATA[java.lang.AssertionError: expected [1.07342614855] but found [0.6351489523872873]
	at com.epam.calculatorTests.CalculatorTests.cotangetOfdouble(CalculatorTests.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- cotangetOfdouble -->
  <testcase name="differenceOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="differenceOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="differenceOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="divisionOfLong" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isPositiveNumber" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isPositiveNumber" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isPositiveNumber" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="multiplicationOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [8868718.08] but found [8868718.0]">
      <![CDATA[java.lang.AssertionError: expected [8868718.08] but found [8868718.0]
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="multiplicationOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [1741642.8496062] but found [1741642.0]">
      <![CDATA[java.lang.AssertionError: expected [1741642.8496062] but found [1741642.0]
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="multiplicationOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests">
    <failure type="java.lang.AssertionError" message="expected [829.98796244] but found [829.0]">
      <![CDATA[java.lang.AssertionError: expected [829.98796244] but found [829.0]
	at com.epam.calculatorTests.CalculatorTests.multiplicationOfDouble(CalculatorTests.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- multiplicationOfDouble -->
  <testcase name="powerOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="powerOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="powerOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="squarerootOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="sumOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="tangentOfDouble" time="0.0" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="tangentOfDouble" time="0.002" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="tangentOfDouble" time="0.001" classname="com.epam.calculatorTests.CalculatorTests"/>
  <testcase name="isNegative" time="0.0" classname="com.epam.calculatorTests.CalculatorTests">
    <ignored/>
  </testcase> <!-- isNegative -->
</testsuite> <!-- UnitTestsforCalculator -->
